# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MarineVerse Blog
email: ahoy@marineverse.com
description: > # this means to ignore newlines until "baseurl:"
  Updates from MarineVerse - all about sailing in Virtual Reality
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.marineverse.com" # the base hostname & protocol for your site
twitter_username: MarineVerseVR
github_username:  marineverse
plugins: ["jekyll-paginate"]
excerpt_separator: <!--more-->
paginate_path: "/blog/archive/:num/"
future: false

# Build settings
markdown: kramdown
paginate: 6
